# Copyright (c) 2026, Sanjay Kumar and contributors
# For license information, please see license.txt
"""
Cross-Conversation Recall for AI Chatbot (Phase 14B.3)

Lightweight alternative to full RAG: searches conversation summaries and
topics from the user's recent conversations to find relevant context when
the user references prior conversations (e.g. "that report I asked about
last week", "same query as before").

Uses conversation summaries (generated by 14B.1) as the search corpus —
no vector store or embeddings needed.
"""

from __future__ import annotations

import json
import re

import frappe

# Signals that the user is referencing a previous conversation
_RECALL_SIGNALS = re.compile(
	r"\b("
	r"last time|before|earlier|previously|"
	r"that report|that query|same (?:query|question|thing|report|analysis)|"
	r"we discussed|we talked|you showed|you said|"
	r"remember when|do you remember|"
	r"again|repeat|redo|re-run|"
	r"last (?:week|month|session|conversation|chat)"
	r")\b",
	re.IGNORECASE,
)

# Maximum number of past conversations to search
_MAX_CONVERSATIONS_TO_SEARCH = 10

# Minimum keyword overlap to consider a conversation relevant
_MIN_MATCH_SCORE = 1


def detect_recall_intent(user_message: str) -> bool:
	"""Check if the user's message references a prior conversation.

	Args:
		user_message: The user's latest message.

	Returns:
		True if the message contains recall signals.
	"""
	return bool(_RECALL_SIGNALS.search(user_message))


def find_relevant_conversations(
	user_message: str,
	current_conversation_id: str | None = None,
	user: str | None = None,
	limit: int = 3,
) -> list[dict]:
	"""Search the user's recent conversations for relevant context.

	Matches are ranked by keyword overlap between the user's message and
	the stored conversation summaries and topics.

	Args:
		user_message: The user's latest message.
		current_conversation_id: Exclude this conversation from results.
		user: Frappe user ID. Defaults to current session user.
		limit: Maximum number of matching conversations to return.

	Returns:
		List of dicts with keys: conversation_id, title, date, summary, topics, score.
		Sorted by score descending (most relevant first).
	"""
	user = user or frappe.session.user
	msg_lower = user_message.lower()

	# Extract keywords from the user message (words >= 4 chars, skip stopwords)
	msg_words = set(_extract_keywords(msg_lower))
	if not msg_words:
		return []

	# Fetch recent conversations with summaries
	conversations = frappe.get_all(
		"Chatbot Conversation",
		filters={
			"user": user,
			"status": "Active",
			"name": ("!=", current_conversation_id or ""),
		},
		fields=["name", "title", "created_at", "session_context"],
		order_by="created_at desc",
		limit_page_length=_MAX_CONVERSATIONS_TO_SEARCH,
	)

	results = []
	for conv in conversations:
		ctx = _parse_session_context(conv.get("session_context"))
		summary = ctx.get("conversation_summary", "")
		topics = ctx.get("conversation_topics", [])

		if not summary and not topics:
			continue

		# Score by keyword overlap
		score = _compute_match_score(msg_words, summary, topics)
		if score >= _MIN_MATCH_SCORE:
			results.append(
				{
					"conversation_id": conv.name,
					"title": conv.title or "Untitled",
					"date": str(conv.created_at)[:10] if conv.created_at else "",
					"summary": summary,
					"topics": topics,
					"score": score,
				}
			)

	# Sort by score descending, take top N
	results.sort(key=lambda r: r["score"], reverse=True)
	return results[:limit]


def build_recall_context(matches: list[dict]) -> str:
	"""Build a context string from matched conversations for system prompt injection.

	Args:
		matches: List of matched conversation dicts from find_relevant_conversations.

	Returns:
		Formatted context string to inject into the conversation.
	"""
	if not matches:
		return ""

	parts = ["## Relevant Previous Conversations"]
	parts.append(
		"The user appears to reference earlier conversations. Here is context from their recent chats:"
	)

	for m in matches:
		date_str = f" on {m['date']}" if m["date"] else ""
		topics_str = f" (topics: {', '.join(m['topics'][:3])})" if m["topics"] else ""
		parts.append(f'\n**From "{m["title"]}"{date_str}:**{topics_str}\n{m["summary"]}')

	parts.append(
		"\nUse this context to inform your response. If the user asks to "
		"repeat or re-run a previous analysis, use the details above to "
		"determine which tools and parameters to use."
	)

	return "\n".join(parts)


# ── Internal helpers ────────────────────────────────────────────────

# Common English stopwords to skip during keyword extraction
_STOPWORDS = frozenset(
	{
		"that",
		"this",
		"what",
		"which",
		"with",
		"from",
		"about",
		"have",
		"been",
		"will",
		"would",
		"could",
		"should",
		"there",
		"their",
		"they",
		"them",
		"then",
		"than",
		"these",
		"those",
		"were",
		"when",
		"where",
		"your",
		"some",
		"more",
		"also",
		"just",
		"like",
		"into",
		"does",
		"done",
		"very",
		"much",
		"many",
		"each",
		"same",
		"show",
		"please",
		"want",
		"need",
		"help",
		"give",
		"make",
		"tell",
	}
)


def _extract_keywords(text: str) -> list[str]:
	"""Extract meaningful keywords from text (words >= 4 chars, no stopwords).

	Args:
		text: Lowercased text to extract keywords from.

	Returns:
		List of keyword strings.
	"""
	words = re.findall(r"[a-z]{4,}", text)
	return [w for w in words if w not in _STOPWORDS]


def _parse_session_context(raw) -> dict:
	"""Parse session_context JSON safely.

	Args:
		raw: Raw JSON string or dict from DB.

	Returns:
		Parsed dict, or empty dict on failure.
	"""
	if not raw:
		return {}
	try:
		return json.loads(raw) if isinstance(raw, str) else raw
	except (json.JSONDecodeError, TypeError):
		return {}


def _compute_match_score(msg_words: set[str], summary: str, topics: list[str]) -> int:
	"""Compute a simple keyword overlap score.

	Each matching keyword in summary or topic labels adds 1 point.
	Topic matches count double because they're more concentrated signals.

	Args:
		msg_words: Set of keywords from the user's message.
		summary: Conversation summary text.
		topics: List of topic labels.

	Returns:
		Integer score (higher = more relevant).
	"""
	score = 0
	summary_lower = summary.lower()

	# Score keyword matches in summary
	for word in msg_words:
		if word in summary_lower:
			score += 1

	# Score keyword matches in topics (double weight)
	topics_text = " ".join(topics).lower()
	for word in msg_words:
		if word in topics_text:
			score += 2

	return score
